---
- hosts: ubuntu:debian
  remote_user: sszabo
  become: yes
  tasks:
  - name: Create aptproxy config
    copy:
      dest: "/etc/apt/apt.conf.d/00aptproxy"
      content: Acquire::http:Proxy "http://192.168.1.10:3142";

  - name: Add Vim 8.0 repository for Xenial systems
    apt_repository:
      repo: ppa:jonathonf/vim
    when: ansible_facts['distribution_major_version'] == "16"

  - name: Upgrade all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: true

  - name: Ensuring vim, git, and snmp are installed for all baseline systems.
    apt:
      name: "{{ packages }}"
      update_cache: yes
      cache_valid_time: 3600
      force_apt_get: true
    vars:
      packages:
      - vim
      - git
      - snmp
      - qemu-guest-agent

  - name: Execute git config to set default user
    command: git config --global user.name "Steve Szabo"

  - name: Execute git config to set default email
    command: git config --global user.email "laszlo.steve@gmail.com"

  - name: Pull Amix vimrc package from github
    command: git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime

  - name: Execute Amix vimrc script
    command: sh ~/.vim_runtime/install_awesome_vimrc.sh

  - name: Baseline apt cleanup
    apt:
      autoclean: yes
