---
- hosts: ansible-tower
  remote_user: sszabo
  become: true

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py
  
  roles:
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
