---
- hosts: k8s
  become: yes
  roles:
    - ruzickap.vmwaretools
    - geerlingguy.git
  tasks:
  - name: Create aptproxy config
    copy:
      dest: "/etc/apt/apt.conf.d/00aptproxy"
      content:
        Acquire::http:Proxy "http://192.168.1.10:3142";

  - name: Add Vim 8.0 repository
    apt_repository:
        repo: ppa:jonathonf/vim

  - name: Update cache and install Vim 8.0
    apt:
        name: vim
        update_cache: yes

  - name: Execute git config to set default user
    command: git config --global user.name "Steve Szabo"

  - name: Execute git config to set default email
    command: git config --global user.email "laszlo.steve@gmail.com"

  - name: Pull Amix vimrc package from github
    command: git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime

  - name: Execute Amix vimrc script
    command: sh ~/.vim_runtime/install_awesome_vimrc.sh

  - name: Install docker-ce dependancy
    apt:
      name: libltdl7

  - name: Install Rancher 2.x supported Docker version
    apt:
      deb: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.3~ce-0~ubuntu-xenial_amd64.deb