- hosts: ubuntu
  become: yes
  tasks:
  - name: Upgrade all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: true
      register: out
  - debug: var=out.stdout_lines