---
- hosts: k8s-nodes
  remote_user: sszabo
  become: yes
  tasks:
    - name: Docker run launching k8s node for laszlo462-k8s-lab
      command: docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.7 --server https://rancher1.lan.laszlo462.com --token d4s5gsjpmbpx9t66k8qtm7nkf7ns75tqfbn45bwngb6ns4cmdjdfxr --ca-checksum 9280b4cbbbc13c599e6bf3a1886d519ecda1bef9747977c1696c0938773cddbf --etcd --controlplane --worker
