---
- hosts: k8s
  remote_user: sszabo
  become: yes
  tasks:
  - name: Install docker-ce dependancy
    apt:
      name: libltdl7
      update_cache: yes

  - name: Install Rancher 2.x supported Docker version
    apt:
      deb: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.3~ce-0~ubuntu-xenial_amd64.deb